project:
  type: website
  output-dir: docs
website:
  title: "mathsresources.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - n5maths.qmd
      - hmaths.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



