project:
  type: website
  output-dir: docs
website:
  title: "mathsresources.github.io"
  navbar:
    left:
      - text: "N5 Maths"
        menu:
        - href: n5mathssept.qmd
          text: "September Assessment"
        - href: n5mathsprelim.qmd
          text: "Prelim Exam"
        - href: n5mathstopup.qmd
          text: "Top-Up Prelim"
        - href: n5mathsexam.qmd
          text: "Final Exam"
      - text: "Higher Maths"
        menu:
        - href: hmathssept.qmd
          text: "September Assessment"
        - href: hmathsnov.qmd 
          text: "November Assessment"
        - href: hmathsprelim.qmd
          text: "Prelim Exam"
        - href: hmathstopup.qmd
          text: "Top-Up Prelim"
        - href: hmathsexam.qmd
          text: "Final Exam"
      - text: "Higher Apps"
        menu:
        - href: happssept.qmd
          text: "September Assessment"
        - href: happsnov.qmd 
          text: "November Assessment"
        - href: happsprelim.qmd
          text: "Prelim Exam"
        - href: happstopup.qmd
          text: "Top-Up Prelim"
        - href: happsexam.qmd
          text: "Final Exam"
      - text: "AH Stats"
        menu:
        - href: ahstatstextbook.qmd
          text: "Textbook"
        - href: ahstatslinks.qmd 
          text: "Useful Links"
    background: primary
format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: true
  


